# https://github.com/release-it/release-it/blob/master/config/release-it.json
git:
  commitMessage: "chore: release v${version}"
github:
  release: true
  releaseName: "v${version}"
npm:
  publish: false
hooks: # https://github.com/release-it/release-it#hooks
  after:init: cd opinionated-review && make test
  after:release: cd opinionated-review && make publish
plugins:
  "@release-it/conventional-changelog": # https://github.com/release-it/conventional-changelog
    preset: angular
