#!/bin/bash

set -e

# theme
echo "===> Using theme 'techbooster'"
cp -r /app/themes/techbooster /app/articles

# copy sources
echo "===> Copying sources to the container"
cp -r /in/* /app/articles
rm -f /app/articles/*.pdf

# build
echo "===> Compiling Re:VIEW sources"
cd /app/articles
bundle exec review-preproc -r --tabwidth=2 *.re
bundle exec review-pdfmaker config.yml

# postprocess
echo "===> Done"
ls *.pdf
cp *.pdf /out/
