#!/bin/bash

set -e

# copy sources
echo "===> Copying sources to the container"
mkdir /app/articles
cp -r /in/* /app/articles
rm -f /app/articles/*.pdf

# build
echo "===> Linting Re:VIEW sources"
cd /app/articles
yarn lint
