version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/opinionated-review"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "docker"
    directory: "/opinionated-review"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
