name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: vibranthq/build-review@master
        with:
          build: ./articles
          dist: ./dist
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ./dist
