name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: vibranthq/build-review@master
      - uses: actions/upload-artifact@master
        with:
          name: Draft
          path: ./dist/ReVIEW-Template-press-ready.pdf
