name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test PDF
        run: make test-pdf
        working-directory: opinionated-review
      - name: Test EPUB
        run: make test-epub
        working-directory: opinionated-review
      - uses: actions/upload-artifact@master
        with:
          name: Artifacts
          path: ./dist
