name: Prepare
on:
  issue_comment:
    types: [created]
jobs:
  manual_prepare:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'member' || github.event.comment.author_association == 'owner') &&
      startsWith(github.event.comment.body, '@shipjs prepare')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: geertvdc/setup-hub@master
      - name: Setup shipjs
        run: |
          cd $HOME
          git clone https://github.com/algolia/shipjs
          cd shipjs
          git checkout fix/gh-action
          cd packages/shipjs
          yarn install
          yarn global add file:$PWD
          echo "::add-path::$HOME/.yarn/bin"
      - name: Prepare
        run: |
          git config user.name "Yasuaki Uechi"
          git config user.email "y@uechi.io"
          git checkout master
          shipjs prepare
          hub api repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments -F "body=\@${GITHUB_ACTOR} \`shipjs prepare\` done with code __${?}__"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
