name: Prepare
on:
  issue_comment:
    types: [created]
jobs:
  manual_prepare:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'member' || github.event.comment.author_association == 'owner') &&
      startsWith(github.event.comment.body, '@shipjs prepare')
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: geertvdc/setup-hub@master
      - run: |
          git config user.name "Yasuaki Uechi"
          git config user.email "y@uechi.io"
      - run: npm i -g shipjs
      - run: shipjs prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
