name: Prepare
on:
  issue_comment:
    types: [created]
jobs:
  manual_prepare:
    if: github.event_name == 'issue_comment' && github.event.comment.author_association == 'OWNER' && startsWith(github.event.comment.body, '@shipjs prepare')
    runs-on: Ubuntu-latest
    steps:
      - run: shipjs prepare
  debug:
    runs-on: Ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event.comment) }}
